/**
 * Created by Arne on 30/01/2017.
 */
export class Order {
    constructor(
        public AfzenderNaam:String,
        public AfzenderStraat:String,
        public AfzenderStad:String,
        public AfzenderLand:String,
        public OntvangerNaam:String,
        public OntvangerStraat:String,
        public OntvangerStad:String,
        public OntvangerPostcode:String,
        public OntvangerLand:String,
        public PlaatsBestemdOntvangstStad:String,
        public PlaatsBestemdOntvangstLand:String,
        public PlaatsOntvangstStad:String,
        public PlaatsOntvangstLand:String,
        public PlaatsOntvangstDatum:String,
        public AantalBijgevoegdeDocumenten:String,
        public MerkenNummers:String,
        public AantalVerpakking:String,
        public TypePallet:String,
        public WijzeVerpakking:String,
        public AardDerGoederen:String,
        public StatistischNummer:String,
        public BrutoGewicht:String,
        public Volume:String,
        public MerkenNummers1:String,
        public AantalVerpakking1:String,
        public TypePallet1:String,
        public WijzeVerpakking1:String,
        public AardDerGoederen1:String,
        public StatistischNummer1:String,
        public BrutoGewicht1:String,
        public Volume1:String,
        public MerkenNummers2:String,
        public AantalVerpakking2:String,
        public TypePallet2:String,
        public WijzeVerpakking2:String,
        public AardDerGoederen2:String,
        public StatistischNummer2:String,
        public BrutoGewicht2:String,
        public Volume2:String,
        public InstructiesAfzender:String,
        public Frankeringsvoorschrift:String,
        public VervoederNaam:String,
        public VervoederStraat:String,
        public VervoederStad:String,
        public VervoederPostcode:String,
        public VervoederLand:String,
        public OpvolgendeVervoederNaam:String,
        public OpvolgendeVervoederStraat:String,
        public OpvolgendeVervoederStad:String,
        public OpvolgendeVervoederPostcode:String,
        public OpvolgendeVervoederLand:String,
        public OpmerkingenVervoerder:String,
        public SpecialeOvereenkomst:String,
        public OpgemaaktPlaats:String,
        public OpgemaaktDatum:String,
    ){}
}